version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: locuventas_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - locuventas_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    image: ${DOCKER_HUB_USER}/locuventas-backend:4.1
    container_name: locuventas_backend
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      APP_ADMIN_NOMBRE: ${APP_ADMIN_NOMBRE}
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads/productos:/app/uploads/productos
      - ./uploads/vendedores:/app/uploads/vendedores
    networks:
      - locuventas_network
    restart: unless-stopped

  frontend:
    image: ${DOCKER_HUB_USER}/locuventas-frontend:4.1
    container_name: locuventas_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - locuventas_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  locuventas_network:
    driver: bridge
