version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: locuventas_db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: locuventas
      MYSQL_USER: locuventas_user
      MYSQL_PASSWORD: secure_user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - locuventas_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    image: dawcarlosp/locuventas-backend:1.0
    container_name: locuventas_backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: locuventas
      DB_USER: locuventas_user
      DB_PASS: secure_user_password
      APP_ADMIN_EMAIL: admin@empresa.com
      APP_ADMIN_PASSWORD: AdminSeguro1234
      APP_ADMIN_NOMBRE: Administrador Principal
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads/productos:/app/uploads/productos
      - ./uploads/vendedores:/app/uploads/vendedores
      - ./uploads/productosprecargados:/app/uploads/productosprecargados
    networks:
      - locuventas_network
    restart: unless-stopped

  frontend:
    image: dawcarlosp/locuventas-frontend:4.4
    container_name: locuventas_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - locuventas_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  locuventas_network:
    driver: bridge
